import Header from "@/components/Header/Header";
import SideMenu from "@/components/SideMenu/SideMenu";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Header />
        <div className="flex flex-col sm:flex-row">
          <div className="w-full sm:w-1/5">
            <SideMenu />
          </div>
          <div className="w-full px-4 pt-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
